{"name": "Проверка ошибки получения заказа из-за отсутсвия его номера", "status": "passed", "start": 1720188158752, "stop": 1720188158831, "uuid": "3c1de957-4cff-4fa7-8d3d-b49dac672cc2", "historyId": "9aaa4011ffe92434149f97eb69e15711", "testCaseId": "9aaa4011ffe92434149f97eb69e15711", "fullName": "tests.test_get_order_by_track.test_get_order_by_track_fail.TestAcceptOrderByTrackFail#test_get_order_without_track_fail", "labels": [{"name": "parentSuite", "value": "tests.test_get_order_by_track"}, {"name": "suite", "value": "test_get_order_by_track_fail"}, {"name": "subSuite", "value": "TestAcceptOrderByTrackFail"}, {"name": "host", "value": "DESKTOP-Q9FKTCA"}, {"name": "thread", "value": "11792-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_track.test_get_order_by_track_fail"}]}