{"name": "Проверка ошибки получения заказа из-за отсутсвия его номера", "status": "passed", "start": 1720032093808, "stop": 1720032093898, "uuid": "76364c76-085c-4d92-afff-969ec9d478a6", "historyId": "9aaa4011ffe92434149f97eb69e15711", "testCaseId": "9aaa4011ffe92434149f97eb69e15711", "fullName": "tests.test_get_order_by_track.test_get_order_by_track_fail.TestAcceptOrderByTrackFail#test_get_order_without_track_fail", "labels": [{"name": "parentSuite", "value": "tests.test_get_order_by_track"}, {"name": "suite", "value": "test_get_order_by_track_fail"}, {"name": "subSuite", "value": "TestAcceptOrderByTrackFail"}, {"name": "host", "value": "DESKTOP-Q9FKTCA"}, {"name": "thread", "value": "1872-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_track.test_get_order_by_track_fail"}]}